# Add your own {OAUTH_TOKEN}, {EXPIRED_TOKEN} and {USER_ID} as string

API_URL = "https://api.spotify.com/v1"
OAUTH_TOKEN = {OAUTH_TOKEN}
EXPIRED_TOKEN = {EXPIRED_TOKEN}
USER_ID = {USER_ID}
HEADERS = {"Authorization": f"Bearer {OAUTH_TOKEN}"}

ALBUM_ID_BELGA_CSUMPA = "6Mo0QD5JOUYI0L18B4sRyd"
ALBUM_ID_AKPH_AKKEZDET = "16tDx6tKDmxMfNQyhfsaIg"
TRACK_URI_NKS_FOLD = "spotify:track:2TpDaiYW03b0aq9UNTkddU"
TRACK_URI_AKPH_MIVEL_JATSZOL = "spotify:track:3RKUUzGXbK43bYShazt1w4"
TRACK_URI_QUEEN_UNDER_PRESSURE = "spotify:track:3M456mM21CoqUmlVxkHUHx"
PLAYLIST_ID_QUEEN_LIVE = "50RDNThwHqz1TjoMLeE53j"
