# Fill in the OAUTH_TOKEN and the USER_ID field with yours

API_URL = "https://api.spotify.com/v1"
OAUTH_TOKEN = {YOUR_OAUTH_TOKEN}
EXPIRED_TOKEN = "BQDUw1iEySSR1Vdcqy1sP-dy21M2zy5GwVhAcEXz8EOO2WiKU4qKMhisd3T9ew0xHjxaSJVGypFRsoPQlrW27FHBynRgNYBCuHwyaouceYWQ-GRCvMOT5DW0XwefrH0ldLFQBV7QGJQ2josSItn_bxZMwKA9TWSj6ZauYWMqc7vgxpdFTshYyqJTpFkKtw0_gGFPDEoSlV-Xyq2vIuTt7kw5mOCOhT0U9i70MlFvTwVgIRC_ZBPF7RIaIHxABpsWCL5F1NjkiOLuk5dxl5w5yM3Arhx3Y9vY98uUgm7z"
USER_ID = {YOUR_USER_ID}
HEADERS = {"Authorization": f"Bearer {OAUTH_TOKEN}"}

ALBUM_ID_BELGA_CSUMPA = "6Mo0QD5JOUYI0L18B4sRyd"
ALBUM_ID_AKPH_AKKEZDET = "16tDx6tKDmxMfNQyhfsaIg"
TRACK_URI_NKS_FOLD = "spotify:track:2TpDaiYW03b0aq9UNTkddU"
TRACK_URI_AKPH_MIVEL_JATSZOL = "spotify:track:3RKUUzGXbK43bYShazt1w4"
TRACK_URI_QUEEN_UNDER_PRESSURE = "spotify:track:3M456mM21CoqUmlVxkHUHx"
PLAYLIST_ID_QUEEN_LIVE = "50RDNThwHqz1TjoMLeE53j"
